import React, { useState } from "react";
import { View, Text, StyleSheet, ScrollView, Alert } from "react-native";
import Header from "../../../components/Header";
import InputField from "../../../components/InputField";
import CustomButton from "../../../components/CustomButton";
import { COLORS } from "../../../constants/colors";
import { linkElderlyUser } from "../../../firebase/firestore";

export default function LinkElderlyScreen({ navigation }) {
  const [linkCode, setLinkCode] = useState("PERERA-72");
  const [relationship, setRelationship] = useState("Daughter");
  const [loading, setLoading] = useState(false);

  const handleLink = async () => {
    if (!linkCode) {
      Alert.alert("Input Error", "Please enter a valid Elderly Link Code.");
      return;
    }

    setLoading(true);
    const res = await linkElderlyUser(linkCode);
    setLoading(false);

    if (res.success) {
      Alert.alert(
        "Successfully Linked! 🎉",
        `You are now connected as caregiver for ${res.elderly.displayName}. You can view real-time status and request help on their behalf.`,
        [
          {
            text: "Go to Dashboard",
            onPress: () => navigation.navigate("CaregiverTab")
          }
        ]
      );
    } else {
      Alert.alert("Link Failed", res.error);
    }
  };

  return (
    <View style={styles.container}>
      <Header
        title="Link Elderly Relative"
        subtitle="Connect via unique invite code"
        role="caregiver"
        onBack={() => navigation.goBack()}
      />

      <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        <View style={styles.card}>
          <View style={styles.iconBadge}>
            <Text style={styles.cardIcon}>🔗</Text>
          </View>
          <Text style={styles.cardTitle}>Elderly Linking Portal</Text>
          <Text style={styles.cardSub}>
            Enter the unique 6-digit code or surname code generated by your elderly relative or provided during setup.
          </Text>

          <InputField
            label="Elderly Link Code"
            value={linkCode}
            onChangeText={setLinkCode}
            placeholder="e.g. PERERA-72"
            icon="key-outline"
          />

          <InputField
            label="Your Relationship (Optional)"
            value={relationship}
            onChangeText={setRelationship}
            placeholder="e.g. Daughter, Son, Niece"
            icon="people-outline"
          />

          <CustomButton
            title="🔗 Connect & Authorize Account"
            variant="primary"
            loading={loading}
            onPress={handleLink}
            style={{ marginTop: 10 }}
          />
        </View>

        <View style={styles.infoBox}>
          <Text style={styles.infoTitle}>💡 How Linking Works:</Text>
          <Text style={styles.infoText}>
            • Caregivers can monitor scheduled visit timelines live from anywhere in the world.
          </Text>
          <Text style={styles.infoText}>
            • Receive push notifications when a volunteer accepts or checks in for a visit.
          </Text>
          <Text style={styles.infoText}>
            • Direct line to contact volunteers and submit emergency reports.
          </Text>
        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.caregiver.bg
  },
  content: {
    padding: 18
  },
  card: {
    backgroundColor: COLORS.white,
    padding: 20,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    marginBottom: 16
  },
  iconBadge: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: COLORS.caregiver.badgeBg,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    marginBottom: 10
  },
  cardIcon: {
    fontSize: 34,
    lineHeight: 44,
    textAlign: "center",
    textAlignVertical: "center",
    includeFontPadding: false
  },
  cardTitle: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "bold",
    color: COLORS.text,
    textAlign: "center",
    includeFontPadding: false
  },
  cardSub: {
    fontSize: 13,
    lineHeight: 18,
    color: COLORS.subtext,
    textAlign: "center",
    marginTop: 4,
    marginBottom: 18,
    includeFontPadding: false
  },
  infoBox: {
    backgroundColor: COLORS.white,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border
  },
  infoTitle: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "bold",
    color: COLORS.caregiver.primary,
    marginBottom: 8,
    includeFontPadding: false
  },
  infoText: {
    fontSize: 13,
    lineHeight: 18,
    color: COLORS.text,
    marginBottom: 6,
    includeFontPadding: false
  }
});

